import leaderboardRaw from "@/data/leaderboard.json";
import type { LeaderboardData } from "@/types/leaderboard";
import type { APIRoute } from "astro";

// sb-ty6 / closes #295 — public stable JSON contract for SynthPanel's
// `--best-model-for` recommendation lookup and any downstream consumer that
// wants the live leaderboard without scraping the site or cloning the repo.
//
// URL: https://synthbench.org/data/leaderboard.json
//
// Stability contract:
//   - `api.version` follows semver. Breaking changes (renames or removals of
//     documented fields) bump major. Additive changes (new optional fields,
//     new entries, new datasets) bump minor.
//   - The `entries` array shape is the canonical contract; new optional fields
//     may be added at any time. Consumers MUST treat unknown fields as opaque.
//   - `generated_at` (ISO 8601 UTC) is the publish timestamp from
//     `synthbench publish-data`. Use it for freshness checks; do not parse the
//     URL or response headers for that.
//   - Cache headers are configured per-deploy in `site/public/_headers`
//     (Cloudflare Pages). Current policy: 1h browser cache, 6h edge cache,
//     stale-while-revalidate up to 24h. Clients SHOULD honor Cache-Control.
//
// SynthPanel's fallback behavior (sy-nkh) treats any non-200 as "use the
// bundled snapshot," so a stale endpoint is still safe — just stale. Removing
// or renaming this URL would break that fallback, so it MUST stay reachable
// at this exact path even if the underlying payload schema evolves.
//
// Docs: docs/leaderboard-json-api.md

// 1.1.0 (P0-4 / P2-4 fix): every score is recomputed from per-question
// data at publish time; ci_lower / ci_upper are now a genuine bootstrap CI
// on the recomputed sps and are `null` (not [0, 0]) when unavailable.
// 1.2.0 (issue #255): additive `entries[].demographic_scorecard` block —
// structured per-dimension subgroup scores from demographic-conditioned
// runs; explicit `null` on entries without demographic data.
// 1.3.0: additive optional `entries[].effort` field — reasoning-effort
// level ("low" | "medium" | "high") threaded to the provider's native
// reasoning knob. Absent on every pre-effort row; absence means provider
// default reasoning behaviour, never "low".
const API_VERSION = "1.3.0";
const CONTRACT_URL =
  "https://github.com/DataViking-Tech/SynthBench/blob/main/docs/leaderboard-json-api.md";

// Cast through unknown because the on-disk leaderboard.json is generated by
// publish.py and is the source of truth; the TS interface tracks it but the
// `as` cast is the trust boundary, identical to every other consumer.
const leaderboard = leaderboardRaw as unknown as LeaderboardData;

export const GET: APIRoute = () => {
  const body = {
    api: {
      version: API_VERSION,
      contract_url: CONTRACT_URL,
      // generated_at duplicated at the top level for consumers that don't
      // want to reach into `api` — keeping both is harmless and avoids
      // breaking the existing internal shape (entries/datasets/etc.) that
      // the site itself imports.
    },
    ...leaderboard,
  };

  return new Response(JSON.stringify(body), {
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      // Cache-Control here is honored by Astro's dev server and by the
      // wrangler-action `pages deploy` upload, but the canonical cache
      // policy for CF Pages is `site/public/_headers`. Keeping it here too
      // is belt-and-suspenders for non-CF hosts.
      "Cache-Control": "public, max-age=3600, s-maxage=21600, stale-while-revalidate=86400",
      "Access-Control-Allow-Origin": "*",
    },
  });
};
