"""Canonical per-question human-distribution registry (sb issue #308).

License-restricted (``gated``) datasets must not ship their per-question
``human_distribution`` in the public git repo. Committed
``leaderboard-results/*.json`` files are therefore *stripped* of the field
(see ``scripts/strip-gated-distributions.py``), and every pipeline step that
genuinely needs the distributions — gated R2 artifact publishing, trusted
tier-2 recompute — rehydrates them from a **canonical source** instead of
trusting (or redistributing) submitter-supplied copies.

Canonical source resolution order (first hit wins):

1. A local per-dataset artifact ``<dir>/<dataset>.json`` where ``<dir>`` is
   ``$SYNTHBENCH_HUMAN_DISTRIBUTIONS_DIR`` or ``~/.synthbench/human-distributions``.
2. The same artifact fetched from the existing gated R2 bucket
   (``human-distributions/<dataset>.json``) when the four ``R2_*`` env vars
   are configured — this is the path CI deploys use. Successful fetches are
   cached into the local directory.
3. The dataset adapter's own ``load()`` (which reads the maintainer's local
   dataset cache, downloading from upstream if absent). Best-effort: any
   adapter failure degrades to "canonical unavailable".

The artifact itself is generated by a maintainer via
``scripts/generate-canonical-distributions.py`` (optionally ``--upload`` to
R2) from the dataset adapters — i.e. from the true upstream data, not from
result files.

This mirrors the question-text registry pattern
(``synthbench.publish._load_question_text_registry``), but the payload is
license-gated so it can never be a committed fixture.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Mapping

logger = logging.getLogger(__name__)

#: R2 object key (and local artifact filename stem) for a dataset's canonical
#: human distributions. Lives in the same gated bucket as the per-question
#: publish artifacts (``synthbench-data-prod``), so the existing deploy
#: credentials cover it and it is never publicly readable.
ARTIFACT_KEY_TEMPLATE = "human-distributions/{dataset}.json"

_ENV_LOCAL_DIR = "SYNTHBENCH_HUMAN_DISTRIBUTIONS_DIR"

# Per-process memoization: (resolved local dir, dataset) → distributions or
# None (None is cached too — a publish pass over 200 files must not retry a
# missing source 200 times).
_CACHE: dict[tuple[str, str], dict[str, dict[str, float]] | None] = {}


def default_local_dir() -> Path:
    """Directory holding local canonical artifacts (env-overridable)."""
    override = os.environ.get(_ENV_LOCAL_DIR)
    if override:
        return Path(override)
    return Path.home() / ".synthbench" / "human-distributions"


def _dataset_base(dataset_name: str) -> str:
    """Strip ``(filter)`` suffixes, mirroring :mod:`synthbench.datasets.policy`."""
    return dataset_name.split(" ", 1)[0].strip()


def build_artifact(dataset_name: str) -> dict:
    """Build the canonical artifact for a dataset from its adapter.

    Loads the dataset through its registered adapter (local cache first,
    upstream download as the adapter's own fallback) and emits::

        {
          "dataset": "<name>",
          "generated_at": "<iso8601>",
          "n_questions": N,
          "distributions": {"<key>": {"<option>": prob, ...}, ...}
        }

    Raises whatever the adapter raises when the source data is unavailable —
    the maintainer script surfaces that directly.
    """
    from synthbench.datasets import DATASETS

    base = _dataset_base(dataset_name)
    adapter_cls = DATASETS.get(base)
    if adapter_cls is None:
        raise KeyError(f"unknown dataset {dataset_name!r}")
    questions = adapter_cls().load()
    distributions = {q.key: dict(q.human_distribution) for q in questions}
    return {
        "dataset": base,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "n_questions": len(distributions),
        "distributions": distributions,
    }


def _parse_artifact(payload: object, source: str) -> dict[str, dict[str, float]] | None:
    if not isinstance(payload, dict):
        logger.warning("canonical artifact %s is not a JSON object", source)
        return None
    dists = payload.get("distributions")
    if not isinstance(dists, dict) or not dists:
        logger.warning("canonical artifact %s has no 'distributions' map", source)
        return None
    out: dict[str, dict[str, float]] = {}
    for key, dist in dists.items():
        if isinstance(dist, dict) and dist:
            out[str(key)] = {str(k): float(v) for k, v in dist.items()}
    return out or None


def _load_from_local_dir(
    base: str, local_dir: Path
) -> dict[str, dict[str, float]] | None:
    path = local_dir / f"{base}.json"
    if not path.exists():
        return None
    try:
        payload = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning("cannot read canonical artifact %s: %s", path, exc)
        return None
    return _parse_artifact(payload, str(path))


def _load_from_r2(base: str, local_dir: Path) -> dict[str, dict[str, float]] | None:
    """Fetch the canonical artifact from the gated R2 bucket, if configured.

    On success the raw artifact is cached into ``local_dir`` so subsequent
    datasets/publish passes in the same environment skip the network hop.
    """
    from synthbench.r2_upload import R2Uploader, env_has_r2_config

    if not env_has_r2_config():
        return None
    key = ARTIFACT_KEY_TEMPLATE.format(dataset=base)
    try:
        payload = R2Uploader.from_env().get_json(key)
    except Exception as exc:  # pragma: no cover - network/creds specific
        logger.warning("R2 fetch of canonical artifact %s failed: %s", key, exc)
        return None
    if payload is None:
        logger.warning("canonical artifact %s not found in R2 bucket", key)
        return None
    parsed = _parse_artifact(payload, f"r2://{key}")
    if parsed is not None:
        try:
            local_dir.mkdir(parents=True, exist_ok=True)
            (local_dir / f"{base}.json").write_text(json.dumps(payload))
        except OSError:  # cache write is best-effort
            pass
    return parsed


def _load_from_adapter(base: str) -> dict[str, dict[str, float]] | None:
    try:
        artifact = build_artifact(base)
    except Exception as exc:
        logger.warning(
            "cannot build canonical distributions for %s from its adapter: %s",
            base,
            exc,
        )
        return None
    return _parse_artifact(artifact, f"adapter:{base}")


def load_canonical_distributions(
    dataset_name: str,
    *,
    local_dir: Path | None = None,
) -> dict[str, dict[str, float]] | None:
    """Return ``{question_key: {option: prob}}`` for a dataset, or ``None``.

    ``None`` means no canonical source is available in this environment;
    callers decide whether that is a warning (untrusted local validation)
    or fatal (strict publish). Results — including misses — are memoized
    per process.
    """
    base = _dataset_base(dataset_name)
    resolved_dir = Path(local_dir) if local_dir is not None else default_local_dir()
    cache_key = (str(resolved_dir), base)
    if cache_key in _CACHE:
        return _CACHE[cache_key]

    dists = (
        _load_from_local_dir(base, resolved_dir)
        or _load_from_r2(base, resolved_dir)
        or _load_from_adapter(base)
    )
    _CACHE[cache_key] = dists
    return dists


def rehydrate_per_question(
    per_question: list,
    distributions: Mapping[str, Mapping[str, float]],
    *,
    replace_existing: bool = False,
) -> int:
    """Fill ``human_distribution`` on per-question rows from a canonical map.

    Mutates rows in place. With ``replace_existing=True`` even rows that
    already carry a distribution are overwritten with the canonical value —
    the trusted-context integrity upgrade (never score against a
    submitter-supplied answer key when the canonical one is available).

    Returns the number of rows still *missing* a distribution afterwards
    (key absent from the canonical map).
    """
    missing = 0
    for row in per_question or []:
        if not isinstance(row, dict):
            continue
        key = row.get("key")
        canonical = distributions.get(key) if isinstance(key, str) else None
        if canonical:
            if replace_existing or not row.get("human_distribution"):
                row["human_distribution"] = dict(canonical)
        elif not row.get("human_distribution"):
            missing += 1
    return missing


def clear_cache() -> None:
    """Reset the per-process memoization (test helper)."""
    _CACHE.clear()


__all__ = [
    "ARTIFACT_KEY_TEMPLATE",
    "build_artifact",
    "clear_cache",
    "default_local_dir",
    "load_canonical_distributions",
    "rehydrate_per_question",
]
