"""Auto-generate the leaderboard PR for `synthbench submit-adapter` (refs #256).

The vendor flow is: ``synthbench submit-adapter ... --open-pr`` writes the
submission artifacts, then this module shells out to ``gh`` to fork the
leaderboard repo into the vendor's namespace, push a submission branch,
and open a PR with body templated from ``submission.md`` + ``run.json``.

SynthBench never reads or stores the vendor's GitHub credentials — ``gh``
uses whatever auth context it already has on the vendor's machine.

The body template is inlined as ``PR_BODY_TEMPLATE`` rather than shipped as
package data: ``[tool.setuptools.package-data]`` is intentionally unset
for the synthbench package (see pyproject.toml — private-holdout integrity model
in #259), so any new on-disk asset would either be skipped from the wheel
or force loosening that contract.
"""

from __future__ import annotations

import base64
import json
import shutil
import subprocess
from pathlib import Path
from typing import Any


EXIT_GH_MISSING = 4


PR_BODY_TEMPLATE = """\
# SynthBench submission: {vendor} ({vendor_version})

**Adapter:** `{adapter_name}` v`{adapter_version}`
**Suite:** `{suite}`
**Run hash:** `{run_hash}`
**Status:** {status}

## Scores

{scores_table}

## Reproducibility

| field | value |
| --- | --- |
| run_hash | `{run_hash}` |
| adapter.name | `{adapter_name}` |
| adapter.version | `{adapter_version}` |
| adapter.vendor | `{vendor}` |
| adapter.vendor_version | `{vendor_version}` |
| suite | `{suite}` |
| schema_version | `{schema_version}` |

The leaderboard CI rebuilds the score table from `raw_responses` in this
submission and compares the recomputed hash against `run_hash`. Tampered
submissions are rejected at PR time.

---

Generated by `synthbench submit-adapter --open-pr`.
"""


class GhUnavailable(RuntimeError):
    """Raised when ``gh`` is not on PATH. The CLI maps this to exit 4."""


class GhCommandFailed(RuntimeError):
    """Raised when a ``gh`` invocation exits non-zero.

    Carries the failing argv + stderr so the CLI layer can surface a
    vendor-actionable error instead of a generic stack trace.
    """

    def __init__(self, argv: list[str], stderr: str) -> None:
        super().__init__(f"gh command failed: {' '.join(argv)}\n{stderr.strip()}")
        self.argv = argv
        self.stderr = stderr


def _format_scores_table(scores: Any) -> str:
    """Render the scores block for the PR body.

    ``scores`` is whatever ``run.json["scores"]`` holds. The scaffold path
    (sb-bas not yet landed) stores ``None``; once the eval pipeline lands
    it's a dict of metric → value. Either shape is rendered safely so the
    PR body always has a scores section.
    """
    if scores is None:
        return (
            "_No scores: this submission was produced in scaffold mode "
            "(eval pipeline pending — see refs #256)._"
        )
    if not isinstance(scores, dict) or not scores:
        return "_(empty)_"

    lines = ["| metric | value |", "| --- | --- |"]
    for key in sorted(scores):
        lines.append(f"| {key} | {scores[key]} |")
    return "\n".join(lines)


def render_pr_body(run_payload: dict[str, Any]) -> str:
    """Build the PR body from a parsed ``run.json`` payload.

    Pure function so it can be unit-tested without touching ``gh``.
    """
    adapter = run_payload.get("adapter") or {}
    return PR_BODY_TEMPLATE.format(
        vendor=adapter.get("vendor", "unknown"),
        vendor_version=adapter.get("vendor_version", "unknown"),
        adapter_name=adapter.get("name", "unknown"),
        adapter_version=adapter.get("version", "unknown"),
        suite=run_payload.get("suite", "unknown"),
        run_hash=run_payload.get("run_hash") or "pending",
        status=run_payload.get("status", "unknown"),
        schema_version=run_payload.get("schema_version", "unknown"),
        scores_table=_format_scores_table(run_payload.get("scores")),
    )


def branch_name(vendor: str, vendor_version: str, run_hash: str | None) -> str:
    """Compute ``submission/<vendor>-<vendor_version>-<run_hash[:8]>``.

    Falls back to ``scaffold`` when no run hash is available so vendors can
    still validate their ``gh`` auth + fork flow against the scaffold path
    (sb-1ix lands the real hash).
    """
    suffix = run_hash[:8] if run_hash else "scaffold"
    safe_vendor = vendor.replace("/", "-").replace(" ", "-")
    safe_version = vendor_version.replace("/", "-").replace(" ", "-")
    return f"submission/{safe_vendor}-{safe_version}-{suffix}"


def _run_gh(argv: list[str], *, cwd: Path | None = None) -> str:
    """Invoke ``gh`` and return stdout. Raises GhCommandFailed on non-zero exit.

    We capture stdout/stderr rather than streaming so the CLI can render a
    single coherent error. If ``gh`` itself is missing we surface that as
    ``GhUnavailable`` before any subprocess call.
    """
    if shutil.which("gh") is None:
        raise GhUnavailable(
            "the `gh` CLI was not found on PATH. Install it from "
            "https://cli.github.com/ and re-run with --open-pr."
        )
    result = subprocess.run(
        ["gh", *argv],
        cwd=str(cwd) if cwd is not None else None,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise GhCommandFailed(["gh", *argv], result.stderr or result.stdout)
    return result.stdout


def open_leaderboard_pr(
    *,
    submission_dir: Path,
    leaderboard_repo: str,
    base_branch: str = "main",
    pr_title: str | None = None,
) -> str:
    """Fork → branch → push → PR.

    Args:
        submission_dir: Directory containing the freshly-written
            ``submission.md`` + ``run.json``.
        leaderboard_repo: Upstream repo in ``owner/name`` form, e.g.
            ``DataViking-Tech/SynthBench``.
        base_branch: Upstream branch to target. Defaults to ``main``.
        pr_title: Optional override; otherwise derived from vendor identity.

    Returns:
        The URL of the opened PR (from ``gh pr create`` stdout).

    Raises:
        GhUnavailable: ``gh`` not on PATH.
        GhCommandFailed: any ``gh`` subcommand exited non-zero.
        FileNotFoundError: submission_dir is missing run.json or submission.md.
    """
    run_path = submission_dir / "run.json"
    md_path = submission_dir / "submission.md"
    if not run_path.exists():
        raise FileNotFoundError(f"run.json not found in {submission_dir}")
    if not md_path.exists():
        raise FileNotFoundError(f"submission.md not found in {submission_dir}")

    payload = json.loads(run_path.read_text())
    adapter = payload.get("adapter") or {}
    vendor = adapter.get("vendor") or "unknown"
    vendor_version = adapter.get("vendor_version") or "unknown"
    branch = branch_name(vendor, vendor_version, payload.get("run_hash"))
    title = pr_title or f"submission: {vendor} ({vendor_version})"
    body = render_pr_body(payload)

    # Fork into the vendor's namespace if no fork exists yet. gh is
    # idempotent here: if a fork already exists it returns 0 with a
    # message. --clone=false / --remote=false because the artifacts are
    # uploaded via the contents API, not via a local clone of the
    # leaderboard tree.
    _run_gh(["repo", "fork", leaderboard_repo, "--clone=false", "--remote=false"])

    # Resolve the authenticated user's login so we can target their fork.
    user_login = _run_gh(["api", "user", "--jq", ".login"]).strip()
    if not user_login:
        raise GhCommandFailed(
            ["gh", "api", "user"],
            "could not determine authenticated GitHub user",
        )
    fork = f"{user_login}/{leaderboard_repo.split('/', 1)[1]}"

    # Get the base branch SHA so we can create our submission branch from it.
    base_sha = _run_gh(
        [
            "api",
            f"repos/{fork}/git/ref/heads/{base_branch}",
            "--jq",
            ".object.sha",
        ]
    ).strip()

    # Create the submission branch ref on the fork.
    _run_gh(
        [
            "api",
            f"repos/{fork}/git/refs",
            "-f",
            f"ref=refs/heads/{branch}",
            "-f",
            f"sha={base_sha}",
        ]
    )

    # Commit submission.md + run.json to the branch via the contents API.
    # One PUT per file; the leaderboard CI only cares about the two files
    # landing on the branch, not about commit shape.
    for path in (md_path, run_path):
        rel = f"submissions/{vendor}/{vendor_version}/{path.name}"
        content_b64 = base64.b64encode(path.read_bytes()).decode("ascii")
        _run_gh(
            [
                "api",
                f"repos/{fork}/contents/{rel}",
                "-f",
                f"message=submission: {vendor} ({vendor_version}) — {path.name}",
                "-f",
                f"content={content_b64}",
                "-f",
                f"branch={branch}",
            ]
        )

    # Open the PR. --head accepts owner:branch when the head is on a fork.
    pr_url = _run_gh(
        [
            "pr",
            "create",
            "--repo",
            leaderboard_repo,
            "--base",
            base_branch,
            "--head",
            f"{user_login}:{branch}",
            "--title",
            title,
            "--body",
            body,
        ]
    ).strip()
    return pr_url
