"""Topic-based question categorization for domain-specific benchmarking.

10-category keyword taxonomy for classifying survey questions.
First-match-wins priority order; deterministic keyword matching only.
"""

from __future__ import annotations

TAXONOMY: dict[str, list[str]] = {
    "Politics & Governance": [
        "elect",
        "vote",
        "party",
        "democrat",
        "republican",
        "congress",
        "president",
        "liberal",
        "conservative",
        "political",
        "legislation",
        "law ",
        "laws ",
        "biden",
        "trump",
        "obama",
        "campaign",
        "ballot",
        "senate",
        "supreme court",
        "governor",
        "mayor",
        "parliament",
        "prime minister",
    ],
    "International Relations & Security": [
        "country",
        "countries",
        "nation",
        "nations",
        "foreign",
        "ally",
        "allies",
        "military",
        "war",
        "nuclear",
        "threat",
        "defense",
        "nato",
        "united nations",
        "diplomacy",
        "superpower",
        "sanctions",
        "territory",
        "territorial",
        "china",
        "russia",
        "iran",
        "iraq",
        "ukraine",
        "germany",
        "france",
        "britain",
        "japan",
        "india",
        "pakistan",
        "africa",
        "europe",
        "asia",
        "middle east",
        "relations with",
        "relations between",
        "world affairs",
        "global",
        "security",
        "terror",
        "peace",
        "conflict",
        "refugee",
        "migration",
    ],
    "Economy & Work": [
        "economy",
        "economic",
        "trade",
        "job ",
        "jobs",
        "employment",
        "unemploy",
        "income",
        "wage",
        "financial",
        "debt",
        "tax",
        "business",
        "invest",
        "inflation",
        "recession",
        "poverty",
        "wealth",
        "rich",
        "poor",
        "working condition",
        "worker",
        "salary",
        "cost of living",
        "afford",
    ],
    "Technology & Digital Life": [
        "technology",
        "internet",
        "online",
        "social media",
        "phone",
        "computer",
        "device",
        "app ",
        "apps",
        "cyber",
        "digital",
        "artificial intelligence",
        "robot",
        "automat",
        "data",
        "privacy",
        "surveillance",
        "monitor",
        "algorithm",
        "software",
    ],
    "Media & Information": [
        "media",
        "news",
        "journalism",
        "journalist",
        "press",
        "newspaper",
        "television",
        "radio",
        "information",
        "misinformation",
        "fake news",
        "censor",
        "freedom of",
    ],
    "Health & Science": [
        "health",
        "medical",
        "doctor",
        "hospital",
        "disease",
        "vaccine",
        "drug",
        "treatment",
        "covid",
        "pandemic",
        "science",
        "scientific",
        "research",
        "environment",
        "climate",
        "pollution",
        "energy",
        "food",
        "water",
        "clean",
    ],
    "Social Values & Religion": [
        "religion",
        "religious",
        "god",
        "church",
        "mosque",
        "muslim",
        "christian",
        "jewish",
        "hindu",
        "buddhist",
        "spiritual",
        "prayer",
        "faith",
        "moral",
        "ethic",
        "abortion",
        "gun",
        "marriage",
        "homosex",
        "gay",
        "family",
        "divorce",
        "sex ",
        "gender",
    ],
    "Identity & Demographics": [
        "immigra",
        "race",
        "racial",
        "ethnic",
        "minority",
        "discrimination",
        "diversity",
        "equal",
        "inequal",
        "bias",
        "prejudice",
        "rights",
        "women",
        "men ",
        "black",
        "white",
        "hispanic",
        "asian",
    ],
    "Trust & Wellbeing": [
        "trust",
        "confidence",
        "favorable",
        "unfavorable",
        "approve",
        "disapprove",
        "opinion of",
        "satisfied",
        "dissatisfied",
        "corrupt",
        "honest",
        "happy",
        "life",
        "wellbeing",
        "well-being",
        "quality of life",
        "ladder",
        "best possible",
        "optimis",
        "pessimis",
        "better or worse",
        "right direction",
        "wrong track",
    ],
}

CATEGORIES: list[str] = list(TAXONOMY.keys()) + ["General Attitudes"]

FALLBACK_CATEGORY: str = "General Attitudes"


def categorize_question(text: str) -> str:
    """Categorize a question into one of the 10 topic categories.

    Uses case-insensitive keyword matching with first-match-wins priority.
    Questions matching no category are assigned to 'General Attitudes'.
    """
    text_lower = text.lower()
    for category, keywords in TAXONOMY.items():
        if any(kw in text_lower for kw in keywords):
            return category
    return FALLBACK_CATEGORY
